language: rust
rust:
    - stable
before_script:
    - rustup component add rustfmt
    - rustup component add clippy
script:
    - cargo fmt --all -- --check
    - cargo clippy -- -D warnings
    - cargo build
    - cargo test
cache: cargo
