language: rust
rust:
    - nightly
before_script:
    - rustup component add rustfmt --toolchain nightly
    - rustup component add clippy --toolchain=nightly
script:
    - cargo +nightly fmt --all -- --check
    - cargo clippy -- -D warnings
    - cargo build
    - cargo test
cache: cargo
