language: rust
rust:
    - nightly
before_script:
    - rustup component add rustfmt --toolchain nightly
script:
    - cargo +nightly fmt --all -- --check
    - cargo build
    - cargo test
cache: cargo
