[package]
name = "pudeuko"
version = "0.1.0"
authors = ["Deseteral <deseteral@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9.9"
chrono = "0.4"
nanoid = "0.2.0"
