[package]
name = "pudeuko"
version = "2.0.0"
authors = ["Deseteral <deseteral@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.9.9"
chrono = "0.4"
nanoid = "0.2.0"
log = "0.4"
fern = "0.5"
message-meta = "0.2"
